### ISSUE TITLE
Datepicker date selected 

### ISSUE THREAD

**Issue by mattpottstj** [aurelia-toolkit/aurelia-toolkit#3]
Hi @MaximBalaganskiy,

I've been using your datepicker plugin but struggling to get the date selection in the popup calendar to auto trigger the value changed event. Is this something that can be done?

Basically using the plugin, I can click in the input or on the clendar button, the calendar popout is presented and i can select a date. Closing the calendar shows the selected date in the input but the change event isn't fired until focus is lost from the input.

What would be ideal would be upon selecting a date and closing the calendar, the actual value is set which will trigger the changed event regardless of focus being lost on the input control.

Kind regards,
Matt

**Comment by MaximBalaganskiy** [comment]
released
